### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by tim-gromeyer** [jcnils/protonhax#10]
Hello :=)

Can you please add install instructions and/or a make install target? This would also help with packaging

**Comment by jcnils** [comment]
Hello,

I can add some instructions and update the Makefile - also, feel free to send a PR.
In general, you just need to be able to call `envload` and `protonhax` from a terminal, and steam being visible to them*.

For Arch, the process can be seen here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=protonhax-git

Something in the lines.
1. Clone the repo, or download from the release page
2.  Open the folder in a terminal
3.  `make` - it will build the envload
4.  Copy `envload` and `protonhax` to where you want to call them from and give proper permissions. e.g `/usr/bin` (but not everyone wants to deploy there)

* For Steam flatpak I need to look into creating a version on flathub.
