### ISSUE TITLE
Run as admin

### ISSUE THREAD

**Issue by M1n-74316D65** [jcnils/protonhax#8]
I want to install Wemod, and it needs admin rights, is there any way to do it?

**Comment by jcnils** [comment]
I am not familiar with Wemod. 
And what do you mean by **admin**? Like root? You should not need to give root permission to proton.

Please provide more details what you are trying to do and what errors you are getting with protohax.

To debug what is happening with the game, could you set launch options and add PROTON_LOG=1

It will be something like this `PROTON_LOG=1 protonhax init %command%` 

Once you run the game, there will be a log file of the game in your home directory, named steam-$GAMEID.log
